name: Deploy Flask App to EC2

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1                     # Cambia a tu región de AWS
  EC2_INSTANCE_IP: 52.91.239.239            # Cambia a la IP pública de tu instancia EC2
  EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}   # Clave privada SSH en formato PEM
  EC2_USER: ubuntu                        # Usuario de la instancia (ec2-user para Amazon Linux)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ env.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem
        echo "Instalada la clave SSH"

    - name: Copy files to EC2
      run: |
        scp -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no -r . ${{ env.EC2_USER }}@${{ env.EC2_INSTANCE_IP }}:/home/${{ env.EC2_USER }}/app

    - name: Deploy application
      run: |
        ssh -i ~/.ssh/ec2_key.pem -o StrictHostKeyChecking=no ${{ env.EC2_USER }}@${{ env.EC2_INSTANCE_IP }} << 'EOF'
        cd /home/${{ env.EC2_USER }}/app
        sudo docker build -t my-flask-app .
        sudo docker stop my-flask-app || true
        sudo docker rm my-flask-app || true
        sudo docker run -d --name my-flask-app -p 80:5000 my-flask-app
        EOF
